<?php
/**
 * Product Flow phtml
 *  _____ _            _               _____                _       
 * /  __ \ |          (_)             |  ___|              | |      
 * | /  \/ | __ _ _ __ _  ___  _ __   | |____   _____ _ __ | |_ ___ 
 * | |   | |/ _` | '__| |/ _ \| '_ \  |  __\ \ / / _ \ '_ \| __/ __|
 * | \__/\ | (_| | |  | | (_) | | | | | |___\ V /  __/ | | | |_\__ \
 *  \____/_|\__,_|_|  |_|\___/|_| |_| \____/ \_/ \___|_| |_|\__|___/
 * 
 * 
 * @category       Clarion
 * @package        Product Flow
 * @copyright      Copyright (c) 2014
 * @license        All Rights Reserved to Clarion Events
 * @author		   Giovanni Capuano <giovanni.capuano@clarionevents.com>
 */
 
