<script type="text/javascript">
	if (typeof jQuery == 'undefined'){
		document.write(unescape("%3Cscript src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
	}
</script>
<div class="label">
	<h2><?php echo Mage::helper('marketplace')->__('Latest Product Added') ?></h2>
</div>
<!-- <div class="best-sell-box" style="display:none;">
	<span class="ed_nav ed_left"></span> -->
	<div class="flexslider">
		<ul class="slides">
			<?php $m= new Mage;
				$version=$m->getVersion();
				$products=$this->getBestsellProducts();
				foreach($products as $productid ){
					$_product=Mage::getModel('catalog/product')->load($productid);
					$stockItem = Mage::getModel('cataloginventory/stock_item');
					$stockItem->loadByProduct($productid);
					//if($stockItem->getData('is_in_stock') == 1 && $_product->getStatus()==1){ 
						?>
				<li>
					<a href="<?php echo $_product->getProductUrl()?>">
						<div class="image">
							<img src=<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(210);?> />
						</div>
					
						<div class="slider-item-content">
							<div class="name"><?php 
							if( strlen($_product->getName()) > 30)
									echo substr($_product->getName(), 0,30) . "...";
								else
									echo $_product->getName();?></div>
							<?php if(floatval($version) < floatval("1.8.0.0")) { ?>
								<div class="price"><?php echo Mage_Catalog_Block_Product::getPriceHtml($_product, true) ?></div> 
							<?php } ?>
						</div>
					</a>
				</li>
				<?php //}
				}
			?>
		</ul>
	
	</div>
	<!-- <span class="ed_nav ed_right"></span> -->
<!-- </div> -->

<script>
$wk_jq=jQuery.noConflict();
(function($wk_jq){	
	// $wk_jq(function(){
		// if($wk_jq('.best-sell .best-sell-product').length > 0){
			// $wk_jq('.best-sell-box').show();
		// }
		// var wk_slider=$wk_jq('.best-sell .best-sell-product').length;
// 
		// $wk_jq('.ed_right').click(function() {
			// if(wk_slider>3)
			// {
			// var thisthis=$wk_jq(this).siblings('.best-sell');
			// thisthis.animate({"left":"-=480"},1500);
			// wk_slider=wk_slider-3;
			// }
		// });
// 		
		// $wk_jq('.ed_left').click(function() {
			// var thisthis=$wk_jq(this).siblings('.best-sell');
			// if(wk_slider<$wk_jq('.best-sell .best-sell-product').length){
				// thisthis.animate({"left":"+=480"},1500);
				// wk_slider=wk_slider+3;
			// }
		// });
	// });
	
	$wk_jq(window).load(function() {
			  $wk_jq('.flexslider').flexslider({
			    animation: "slide",
			    animationLoop: false,
			    slideshow: false,
			    itemMargin: 10,
			    minItems: 2,
			    maxItems: 4,
			    controlNav:false
			  });
		  });
})($wk_jq);
</script>