<?php
	$helper=Mage::helper('customoption');
?>
<li>
	<label><?php echo $helper->__('Custom Option') ?> :</label>
	<div class="input-box wk_customoptionwidth">
		<button class="button addcusop" type="button" title="<?php echo $helper->__('Add New Option') ?>" id="add_new_defined_option"><span><span><span><?php echo $helper->__('Add New Option') ?></span></span></span></button>
		<div id="coption">
			<input type="hidden" name="customcount" value="0" id="customcount" />
			<input type="hidden" name="customcountallid" value="0" id="customcountallid" />
			<div id="othercustomoption"></div>
			<div class="wk_clear"></div>
		</div>
	</div>
</li>					
<script> 
(function($wk_jq){
	var ct=0;
	$wk_jq('.addcusop').click(function(){
		var deletebutton=$wk_jq('#add_new_defined_option').clone();
		deletebutton.removeAttr('id')
				    .removeClass('addcusop')
				    .addClass('removeCustomOption')
				    .find('span span span').text('<?php echo $helper->__(' Delete Option ')?>');
		var inputtype=$wk_jq('<select/>',{'name':'options['+ct+'][type]'})
								.attr('data_option_index',ct)
								.addClass('required-entry customoption_type')
								.append($wk_jq('<option/>',{'value':''}).text('- - - -'))
								.append($wk_jq('<optgroup/>',{'label':'Text'})
									.append($wk_jq('<option/>')
												.attr('value','field')
											    .text("<?php echo $helper->__(' Field ') ?>"))
								    .append($wk_jq('<option/>')
												.attr('value',"area")
											    .text("<?php echo $helper->__(' Area ') ?>")))
								.append($wk_jq('<optgroup/>',{'label':'File'})
									.append($wk_jq('<option/>')
												.attr('value','file')
												.text("<?php echo $helper->__(' File ') ?>")))
								.append($wk_jq('<optgroup/>',{'label':'Select'})
									.append($wk_jq('<option/>')
												.attr('value',"drop_down")
												.text("<?php echo $helper->__('Drop Down') ?>"))
									.append($wk_jq('<option/>')
												.attr('value',"radio")
												.text("<?php echo $helper->__(' Radio Buttons ') ?>"))
									.append($wk_jq('<option/>')
												.attr('value',"checkbox")
												.text("<?php echo $helper->__(' Checkbox ') ?>"))
									.append($wk_jq('<option/>')
												.attr('value',"multiple")
												.text("<?php echo $helper->__(' Multi Select ') ?>")))
								.append($wk_jq('<optgroup/>',{'label':'Date'})
									.append($wk_jq('<option/>')
												.attr('value',"date")
												.text("<?php echo $helper->__(' Date ') ?>"))
									.append($wk_jq('<option/>')
												.attr('value',"date_time")
												.text("<?php echo $helper->__(' Date & Time ') ?>"))
									.append($wk_jq('<option/>')
												.attr('value',"time")
												.text("<?php echo $helper->__(' Time ') ?>")));
		var isrequired=$wk_jq('<select/>',
							{'name':'options['+ct+'][is_require]'})
							.append($wk_jq('<option/>').attr('value',"1").text("<?php echo $helper->__(' Yes ') ?>"))
							.append($wk_jq('<option/>').attr('value',"0").text("<?php echo $helper->__(' No ') ?>"));
														
		var customoption=$wk_jq('<div/>')
							.addClass('customoption')
							// .append($wk_jq('<div/>')
									// .addClass('head')
									// .append($wk_jq('<span/>')
												// .addClass('label')
												// .text('<?php //echo $helper->__(' Title ')?>')
												// .append($wk_jq('<em/>').text('*')))
									// .append($wk_jq('<span/>')
												// .addClass('label')
												// .text('<?php //echo $helper->__(' Input Type ')?>')
												// .append($wk_jq('<em/>').text('*')))
									// .append($wk_jq('<span/>')
												// .addClass('label')
												// .text('<?php //echo $helper->__(' Is Required ')?>'))
									// .append($wk_jq('<span/>')
												// .addClass('label')
												// .text('<?php //echo $helper->__(' Sort Order ')?>'))
									// .append(deletebutton)
									// )
						 	.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Title ')?>')
												.append($wk_jq('<em/>').text('*')))
							.append($wk_jq('<input/>',{'type':'text','name':'options['+ct+'][title]'})
										.addClass('required-entry'))
							.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Input Type ')?>')
												.append($wk_jq('<em/>').text('*')))
							.append(inputtype)
							.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Is Required ')?>'))
							.append(isrequired)
							.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Sort Order ')?>'))
							.append($wk_jq('<input/>',{'type':'text','name':'options['+ct+'][sort_order]'}))
							.append($wk_jq('<input/>',{'type':'hidden','name':'options['+ct+'][customoptindex]','value':ct}))
							.append($wk_jq('<div/>')
									.addClass('head')
									.append(deletebutton)
								);
			$wk_jq('#othercustomoption').append(customoption);
			ct++;										
										  
	});
	
	$wk_jq('#othercustomoption').delegate('.customoption_type','change',function(){
			var text=['field','area','date','date_time','time'];
			var select=['drop_down','radio','checkbox','multiple'];
			var thisobj=$wk_jq(this);
			var optindex=thisobj.attr('data_option_index');
			var pricetype=$wk_jq('<select/>',{'name':'options['+optindex+'][price_type]'})
								.addClass('required-entry')
								.append($wk_jq('<option/>',{'value':'fixed'})
											.text('<?php echo $helper->__(' Fixed ')?>'))
								.append($wk_jq('<option/>',{'value':'percent'})
										.text('<?php echo $helper->__(' Percent ')?>'));
			if($wk_jq.inArray(thisobj.val(),text)>=0){
				var optionvalue=$wk_jq('<div/>')
							.addClass('customoption')
							.append($wk_jq('<div/>')
									.addClass('head')
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Price ')?>'))
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Price Type ')?>'))
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' SKU ')?>'))
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Max Characters ')?>'))
									)
							.append($wk_jq('<div/>',{'class':'wk_row'})
							.append($wk_jq('<input/>',{'type':'text','name':'options['+optindex+'][price]'})
													.addClass('validate-number'))
							.append(pricetype)
							.append($wk_jq('<input/>',{'type':'text','name':'options['+optindex+'][sku]'}))
							.append($wk_jq('<input/>',{'type':'text','name':'options['+optindex+'][max_characters]'})));
					if(thisobj.val()=='date'||thisobj.val()=='date_time'||thisobj.val()=='time'){
						optionvalue.find('.label:last').remove();
						optionvalue.find('input:last').remove();
					}
					thisobj.parents('.customoption').find('.customoption').remove();
					thisobj.parents('.customoption').append(optionvalue);
			}else if($wk_jq.inArray(thisobj.val(),select)>=0){
				var deletebutton=$wk_jq('#add_new_defined_option').clone();
					deletebutton.removeAttr('id')
								.removeClass('addcusop')
								.attr('title','<?php echo $helper->__(' Delete Option ') ?>')
								.removeClass('removeCustomOption')
								.addClass('removeOption')
								.addClass('delete')
								.find('span span span').text('<?php echo $helper->__(' X ')?>');
				var addoptbutton=$wk_jq('#add_new_defined_option').clone();
					addoptbutton.removeAttr('id')
								.removeClass('addcusop')
								.attr('title','<?php echo $helper->__(' Add Option ') ?>')
								.removeClass('removeCustomOption')
								.addClass('addOption')
								.find('span span span').text('<?php echo $helper->__(' Add Option ')?>');
				var optionvalue=$wk_jq('<div/>')
							.addClass('customoption')
							.append($wk_jq('<div/>')
									.addClass('head')
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Title ')?>')
												.append($wk_jq('<em/>').text('*')))
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Price ')?>'))
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Price Type ')?>'))
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' SKU ')?>'))
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__(' Short Order ')?>'))
									.append($wk_jq('<span/>')
												.addClass('label')
												.text('<?php echo $helper->__('')?>'))
									)
							.append(addoptbutton);
					thisobj.parents('.customoption').find('.customoption').remove();
					thisobj.parents('.customoption').append(optionvalue);
					thisobj.parents('.customoption').find('.addOption').trigger('click');
					
			}else if(thisobj.val()=='file'){
				var optionvalue=$wk_jq('<div/>')
					.addClass('customoption')
					.append($wk_jq('<div/>')
							.addClass('head')
							.append($wk_jq('<span/>')
										.addClass('label')
										.text('<?php echo $helper->__(' Price ')?>'))
							.append($wk_jq('<span/>')
										.addClass('label')
										.text('<?php echo $helper->__(' Price Type ')?>'))
							.append($wk_jq('<span/>')
										.addClass('label')
										.text('<?php echo $helper->__(' SKU ')?>'))
							.append($wk_jq('<span/>')
										.addClass('label')
										.text('<?php echo $helper->__(' Allowed File Extensions ')?>'))
							.append($wk_jq('<span/>')
										.addClass('label')
										.text('<?php echo $helper->__(' Maximum Image Size ')?>'))
							)
					.append($wk_jq('<div/>',{'class':'wk_row'})
						.append($wk_jq('<input/>',{'type':'text','name':'options['+optindex+'][price]'})
							.addClass('validate-number'))
						.append(pricetype)
						.append($wk_jq('<input/>',{'type':'text','name':'options['+optindex+'][sku]'}))
						.append($wk_jq('<input/>',{'type':'text','name':'options['+optindex+'][file_extension]'}))
						.append($wk_jq('<span/>',{'class':'file_size'})
							.append($wk_jq('<input/>',{'type':'text','name':'options['+optindex+'][image_size_x]'}))
							.append($wk_jq('<input/>',{'type':'text','name':'options['+optindex+'][image_size_y]'}))
						)
					);
			thisobj.parents('.customoption').find('.customoption').remove();
			thisobj.parents('.customoption').append(optionvalue);
		}	
	});
	$wk_jq('#othercustomoption').delegate('.removeCustomOption','click',function(){
		$wk_jq(this).parents('.customoption').remove();
	});
	$wk_jq('#othercustomoption').delegate('.removeOption','click',function(){
		$wk_jq(this).parents('.wk_row').remove();
	});
	$wk_jq('#othercustomoption').delegate('.addOption','click',function(){
			var selectoptindx=$wk_jq(this).parent('.customoption').parents('.customoption').find('.customoption_type').attr('data_option_index');
			var deletebutton=$wk_jq('#add_new_defined_option').clone();
					deletebutton.removeAttr('id')
								.removeClass('addcusop')
								.attr('title','<?php echo $helper->__(' Delete Option ') ?>')
								.removeClass('removeCustomOption')
								.addClass('removeOption')
								.addClass('delete')
								.find('span span span').text('<?php echo $helper->__(' X ')?>');
			var optindex=0;
			var tempdata=$wk_jq(this).parent('.customoption').find('.wk_row:last input:first').attr('name');
			if(tempdata!=undefined){
				optindex=parseFloat(tempdata.split('[')[2].split(']')[0])+1;	
			}
			var pricetype=$wk_jq('<select/>',{'name':'selectoptions['+selectoptindx+']['+optindex+'][price_type]'})
								.addClass('required-entry')
								.append($wk_jq('<option/>',{'value':'fixed'})
											.text('<?php echo $helper->__(' Fixed ')?>'))
								.append($wk_jq('<option/>',{'value':'percent'})
										.text('<?php echo $helper->__(' Percent ')?>'));					
			var $wk_row=$wk_jq('<div/>',{'class':'wk_row'})
							.append($wk_jq('<input/>',{'type':'text','name':'selectoptions['+selectoptindx+']['+optindex+'][title]'})
													.addClass('required-entry'))
							.append($wk_jq('<input/>',{'type':'text','name':'selectoptions['+selectoptindx+']['+optindex+'][price]'})
													.addClass('validate-number'))
							.append(pricetype)
							.append($wk_jq('<input/>',{'type':'text','name':'selectoptions['+selectoptindx+']['+optindex+'][sku]'}))
							.append($wk_jq('<input/>',{'type':'text','name':'selectoptions['+selectoptindx+']['+optindex+'][short_order]'}));
		if($wk_jq(this).parent('.customoption').find('.wk_row').length > 0){
			$wk_row.append(deletebutton);
		}	
		$wk_jq(this).before($wk_row);
	});
	
})(jQuery);

</script>
