<?php
/**
 * @author Ecommerce Approch Team
 * @copyright Copyright (c) 2015 Ecommerce Approch (http://www.ecommerceapproach.com/)
 * @package Ecommerceapp_Emailsubscribe
 
 * @see Ecom_Emailsubscribe_Block_Checkout_Agreements
 */
?>
<?php if (!$this->getAgreements() && !$this->getHelper()->isEnabled()) return; ?>
<form action="" id="checkout-agreements" onsubmit="return false;">
<?php
if ($this->getHelper()->isEnabled()): // Show if extension enabled 
	if (!$this->getHelper()->isAlreadySubscribed()): // if user already subscribed option will not show
?>
<style>
#emailsubscribe{ float:left;} 
</style>
		<div class="buttons-set">
			<ul class="form-list">
				<li>
					<div>
						<input type="checkbox" id="emailsubscribe" class="checkbox" name="emailsubscribe[subscribe]" value="1"<?php if($this->getHelper()->checkboxChecked()) { ?> checked="checked"<?php } ?> />
						<label for="emailsubscribe"><?php echo $this->getHelper()->getDefaultTitle(); ?></label>
					</div>
				</li>
			</ul>
		</div>
<?php 
	endif;
endif;
?>	



<?php if (!$this->getAgreements()): ?>
	<ol class="checkout-agreements">
	<?php foreach ($this->getAgreements() as $_a): ?>
		<li>
			<div class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
				<?php if ($_a->getIsHtml()):?>
					<?php echo $_a->getContent() ?>
				<?php else:?>
					<?php echo nl2br($this->escapeHtml($_a->getContent())) ?>
				<?php endif; ?>
			</div>
			<p class="agree">
				<input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->escapeHtml($_a->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $_a->getIsHtml() ? $_a->getCheckboxText() : $this->escapeHtml($_a->getCheckboxText()) ?></label>
			</p>
		</li>
	<?php endforeach ?>
	</ol>
 <?php endif; ?>
</form>
