
<link href="<?php echo Mage::getBaseUrl('skin')?>frontend/default/default/css/zero_slider.css" type="text/css" media="all" rel="stylesheet" />
<!-- Skitter JS -->
	<script type="text/javascript" language="javascript" src="<?php echo Mage::getBaseUrl('skin')?>frontend/default/default/js/slider/jquery-1.6.3.min.js"></script>
	<script type="text/javascript" language="javascript" src="<?php echo Mage::getBaseUrl('skin')?>frontend/default/default/js/slider/jquery.easing.1.3.js"></script>
	
	<script type="text/javascript" language="javascript" src="<?php echo Mage::getBaseUrl('skin')?>frontend/default/default/js/slider/zero_slider.js"></script>
	<?php  $configData = Mage::getStoreConfig('slider');?>
	<!-- Init Skitter -->
	<script type="text/javascript" language="javascript">
		$(document).ready(function() {
			$('.box_skitter_large').skitter({
			theme: '<?php echo $configData['image']['theme']?>',
				
				label: <?php echo $configData['image']['show_description']?>,
				progressbar: <?php echo $configData['image']['show_progressbar']?>, 
				animation: '<?php echo $configData['image']['animation']?>',
				numbers: <?php echo $configData['image']['show_number']?>,
				navigation:<?php echo $configData['image']['show_navbar']?>,
			});
			
			
			
			
		});
	</script>
    
     <?php
         $width=Mage::getStoreConfig('slider/image/image_width');
		$height=Mage::getStoreConfig('slider/image/image_height');
		?>
    <style>
	.box_skitter_large {
	width: <?php echo $width?>;
	height: <?php echo $height.'px'?>;
	max-width: 900px;
	margin:auto;
}

.box_skitter img {
	width: <?php echo $width?>;
	height:<?php echo $height.'px'?>;
	
} 

	</style>
        
        
        <?php
		//echo $configData['image']['theme'].'<br>';
		//echo $configData['image']['animation'].'<br>';
		//echo Mage::getBaseUrl('skin');
		?>
        <?php $my=Mage::getModel('slider/slider')->getCollection()->addFieldToFilter('status',Array('eq'=>'Enabled'))->addOrder('zero_id', 'desc'); 
		/* $my->addFieldToFilter(array(
array('attribute'=>'status','eq'=>'Enabled'),
));*/
		?>
        <?php // foreach($my as $contact) {?>
        <?php // echo $contact->getData('nom')?>
         <?php  //echo $contact->getData('status')?>
        <!-- <img src="<?php //echo Mage::getBaseUrl('skin')?>/frontend/default/default/images/slider_image/<?php //echo $contact->getData('slider_image')?>" width="<?php echo $width?>" 
         height="<?php echo $height?>"/><br />-->
        <?php //} ?>
        <div class="box_skitter box_skitter_large">
					<ul>
                     <?php  foreach($my as $contact) {?>
						<li><a href="http://<?php echo $contact->getData('imagelink')?>" target="_blank"><img src="<?php echo Mage::getBaseUrl('skin')?>frontend/default/default/images/slider_image/<?php echo $contact->getData('slider_image')?>" width="<?php echo $width?>" 
         height="<?php echo $height?>"/></a><div class="label_text"><p><?php echo $contact->getData('label')?></p></div></li>
						
                         <?php } ?>	
					</ul>
				</div>
        
        
       
