<?php
/**
 * @title	   Nochex Checkout Module
 * @package    NochexLTD_Nochex
 * @copyright  Copyright (c) 2011 Nochex LTD. (http://www.nochex.com)
 * @author 	   Nochex 
 **/
?>

<fieldset class="form-list">

	<a style="float:left;" href="https://nochex.com/"><img src="https://www.nochex.com/logobase-secure-images/nochex_standard_logo_125x35.gif" alt="Nochex - Online Payment Services" width="125" height="35"/></a>
    <?php $_code=$this->getMethodCode() ?>
	
	
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to the Nochex payment pages when you place an order.') ?>
        </li>
    </ul>
</fieldset>

